package escuelaing.edu.co.patrones.model;

import jakarta.persistence.*;

/**
 * Entity class that represents a user in the system.
 * This class is mapped to the "users" table in the database.
 */
@Entity
@Table(name = "users")

public class User {
    /**
     * The unique identifier for the user.
     * Automatically generated by the database using an auto-increment strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false)
    private String password;

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
